name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.LEIALOFT_DEVELOPMENT_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.LEIALOFT_DEVELOPMENT_AWS_SECRET_ACCESS_KEY_ID }}
          aws-region: us-east-1
      - uses: ./
        with:
          repo-name: 'leialoft-service'
          qtd-images: 6
